version: '3'
services:
  web:
    build: server/
    image: tanema/oopp-group-46
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GOGREEN_MAIL_PASSWORD: ${GOGREEN_MAIL_PASSWORD}
      GOGREEN_MAIL_USER: ${GOGREEN_MAIL_USER}
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - coapi
  coapi:
    build: co-api/
    image: tanema/oopp-group-46-co-api
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
