-- Inserting authorities
INSERT INTO AUTHORITY (AID, NAME) VALUES ('0', 'USER_AUTHORITY') ON CONFLICT DO NOTHING;
INSERT INTO AUTHORITY (AID, NAME) VALUES ('1', 'ADMIN_AUTHORITY') ON CONFLICT DO NOTHING;

-- Inserting base user
INSERT INTO USER_TABLE (USER_ID, ACC_ACTIVATED, ACC_EXPIRED, ACC_LOCKED, PASSWORD, NAME) VALUES ('054597382efa45f5b3cfebcdb16d6cd4', 'true', 'false', 'false', '$2a$10$67OBfdBphsEdLr7hlD2XDOA1USyt5jCqJMmMUiByemWtRrbKObFfi', 'admin') ON CONFLICT DO NOTHING;
INSERT INTO USER_PROFILE (PROFILE_ID, USER_ID, POINTS) VALUES ('056573882efa45f5b3cfebcdb16d1cd4', '054597382efa45f5b3cfebcdb16d6cd4', '0') ON CONFLICT DO NOTHING;
INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES ('054597382efa45f5b3cfebcdb16d6cd4', '0') ON CONFLICT DO NOTHING;
INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES ('054597382efa45f5b3cfebcdb16d6cd4', '1') ON CONFLICT DO NOTHING;

-- Inserting categories
INSERT INTO CATEGORY (ID, NAME, DESCRIPTION) VALUES ('0', 'Food', 'Food items'), ('1', 'Transport', 'Transportation'), ('2', 'Energy', 'Energy items'), ('3', 'Misc', 'Other items') ON CONFLICT DO NOTHING;

-- Inserting activities
-- Category: Food (0)
--   Activity: Eating vegetarian meal
INSERT INTO ACTIVITY (ID, NAME, DESCRIPTION, CATEGORY) VALUES (0, 'Vegetarian meal', 'Eat a vegetarian meal', 0) ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (0, 'SUBMITTED_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (0, 'COMPLETED_FOOD_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (0, 'ATE_VEGETARIAN_MEAL') ON CONFLICT DO NOTHING;
INSERT INTO ACTIVITY_OPTION (ID, DESCRIPTION, INPUT_TYPE, ACTIVITY) VALUES (0, 'Amount of meals', 'FLOAT', 0) ON CONFLICT DO NOTHING;

-- Category: Transport (1)
INSERT INTO ACTIVITY (ID, NAME, DESCRIPTION, CATEGORY) VALUES (1, 'Biking', 'Use your bike instead of the bus', 1) ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (1, 'SUBMITTED_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (1, 'COMPLETED_TRANSPORT_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (1, 'USED_BIKE_INSTEAD_BUS') ON CONFLICT DO NOTHING;
INSERT INTO ACTIVITY_OPTION (ID, DESCRIPTION, INPUT_TYPE, ACTIVITY) VALUES (1, 'Kilometers biked', 'FLOAT', 1) ON CONFLICT DO NOTHING;

-- Category: Energy (2)

-- Category: Misc (3)
INSERT INTO ACTIVITY (ID, NAME, DESCRIPTION, CATEGORY) VALUES (2, 'Tree planting', 'Plant a tree in your garder', 3) ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (2, 'SUBMITTED_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (2, 'COMPLETED_MISC_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO TRIGGERS (ID, TRIGGER) VALUES (2, 'PLANTED_TREE') ON CONFLICT DO NOTHING;
INSERT INTO ACTIVITY_OPTION (ID, DESCRIPTION, INPUT_TYPE, ACTIVITY) VALUES (2, 'Trees planted', 'FLOAT', 2) ON CONFLICT DO NOTHING;

--INSERT INTO ACTIVITY (ID, NAME, DESCRIPTION, CATEGORY) VALUES (1, 'Eating a veg meal', 'description', '1'), (2, 'Using bike instead of car', 'description', '2'), (3, 'Reducing heating', 'description', '3'), (4, 'Planting a garden', 'description',  '4');

-- Inserting badges
INSERT INTO BADGE (ID, NAME, MESSAGE, TRIGGER) VALUES (0, 'Completed activity', 'You completed an activity!', 'SUBMITTED_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO BADGE (ID, NAME, MESSAGE, TRIGGER) VALUES (1, 'Completed food activity', 'You completed a food activity!', 'COMPLETED_FOOD_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO BADGE (ID, NAME, MESSAGE, TRIGGER) VALUES (2, 'Completed transport activity', 'You completed a food activity!', 'COMPLETED_TRANSPORT_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO BADGE (ID, NAME, MESSAGE, TRIGGER) VALUES (3, 'Completed energy activity', 'You completed a food activity!', 'COMPLETED_ENERGY_ACTIVITY') ON CONFLICT DO NOTHING;
INSERT INTO BADGE (ID, NAME, MESSAGE, TRIGGER) VALUES (4, 'Completed miscellaneous activity', 'You completed a miscellaneous activity!', 'COMPLETED_MISC_ACTIVITY') ON CONFLICT DO NOTHING;